### ISSUE TITLE
Website: improvement

### ISSUE THREAD

**Issue by gretanausedaite** [iTwin/iTwinUI#941]
Issue to track some improvements needed in website:

- [ ] Short description of components needs to be updated. No more than 3 lines without the concat.
- [ ] Split `index.astro` code into more components. Right now it's a mess with everything in one place and a lot of repetitive code.
- [ ] Add version note somewhere in docs.
- [ ] Move card/tiles to React component (for better polymorphism support)
- [x] Add a "See also"/"Related" section with links to the related components ([comment](https://github.com/iTwin/iTwinUI/pull/944#issuecomment-1370099053)) #1185 
- [x] Ability to highlight specific lines in code blocks. Maybe using [`expressive-code`]( https://github.com/expressive-code/expressive-code).
- [x] Fix sitemap
- [ ] Add FAQ (from our wiki)
- [x] Add search functionality: #1365
- [ ] Add theme switcher to examples
- [x] Add "related content" to docs pages
- [ ] Collapsable side nav areas
- [ ] Document exported util functions, components and hooks
- [x] Scrollbar looks wider than in css/storybook examples
- [x] Home screen example be clickable #1191 
- [x] Add link to Figma component library. #1358
- [ ] Mention browser targets. ([comment](https://github.com/iTwin/iTwinUI/pull/1418#discussion_r1269099636))
- [x] Props table styling messed up ([comment](https://github.com/iTwin/iTwinUI/pull/1539#pullrequestreview-1611137568))
- [ ] Missing Props tables for sub components (example: [tabs](https://dev-itwinui.bentley.com/docs/tabs) only lists props for the legacy api)
- [ ] Add a basic usage under each (or most) "Usage" sections on the docs site. E.g. [Input](https://dev-itwinui.bentley.com/docs/input#usage), [ToggleSwitch](https://dev-itwinui.bentley.com/docs/toggleswitch#usage), [Breadcrumbs](https://dev-itwinui.bentley.com/docs/breadcrumbs#usage). ([#1999 (comment)](https://redirect.github.com/iTwin/iTwinUI/pull/1999#discussion_r1568969830))
- [ ] Maybe document how users can extend our theme colors to match their color theme. E.g. how to change their accent color but keep all other colors the same, etc.

Far future:
- [ ] Guide pages (short "tutorials" how to do things)

**Comment by FlyersPh9** [comment]
Do you want help with this:

> Short description of components needs to be updated. No more than 3 lines without the concat.

We might be able to get some help from Jay Brady, Jason Coleman, or Michelle Dillard.

**Comment by mayank99** [comment]
Reposting https://github.com/iTwin/iTwinUI/pull/1088#issuecomment-1448519195 here for visibility:
> > I'm a bit worried these code samples takes too much space in docs (eg. alert). Especially if only one prop value is changing.
>
> Yeah.. I alluded to this earlier - we should find a way to _highlight a single line of code_, and describe that the prop can be adjusted. Also, we don't need to show every single permutation and not everything needs a full example, so we should find a way to _show only demo or only code_ instead of always showing both.
>
> I've also been thinking about reorganizing the pages so that examples, writing, and props table live in separate tabs within the same page. This will especially come in handy for bigger components (e.g. Table) which need lots of written documentation but also need lots of examples.

**Comment by FlyersPh9** [comment]
I explored an alternative design in #1166 for the code samples that take up a little less vertical space.  Leaving this here if we decide to revisit the topic.

**Comment by FlyersPh9** [comment]
The scrollbar for the website is being applied to the `<Textarea>` demos: https://github.com/iTwin/iTwinUI/pull/1178#issuecomment-1492415433

**Comment by FlyersPh9** [comment]
Increase the visual separation so demos from previous sections aren't confused with the section beneath. https://github.com/iTwin/iTwinUI/pull/1180#discussion_r1160201671
